# .github/workflows/deploy.yml

name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: Deploy to my Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: yarn
          cache-dependency-path: './package-lock.json'

      - name: build website
        run: 
          yarn add 
          yarn add remark-math@6 rehype-katex@7 
          yarn build

      - name: Deploy to my Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build